# -- Scalars --
scalar Date
scalar Time
scalar DateTime
scalar JSON
scalar ANY

# -- Directives --
directive @metadata on OBJECT
directive @input on OBJECT
directive @type on OBJECT
directive @entity on OBJECT
directive @expression on OBJECT
directive @crud(auth: JSON) on FIELD_DEFINITION
directive @query(auth: JSON) on FIELD_DEFINITION
directive @mutation(auth: JSON) on FIELD_DEFINITION
directive @relation(type: RelationType) on FIELD_DEFINITION

# -- Roots --
schema {
  query: Query
  mutation: Mutation
}
type Query {
  Metadata: MetadataRegistry
}
type Mutation {
  ping(input: ANY): ANY
}

# -- Enums --
enum RelationType {
  OneToOne,
  OneToMany,
  ManyToOne
}
enum OnOff {
  On,
  Off
}

# -- API: HelloWorld --#
extend type Query {
  HelloWorld_test(req: TestInput): TestResult @public(api: "HelloWorld", method: "test", roles: { Internal: true, External: true, Remote: true, Public: true })
  HelloWorld_testLiteral(req: String): [String] @public(api: "HelloWorld", method: "testLiteral", roles: { Internal: true, External: true, Remote: true, Public: true })
  HelloWorld_testVoid: [String] @public(api: "HelloWorld", method: "testVoid", roles: { Internal: true, External: true, Remote: true, Public: true })
  HelloWorld_testEnum(state: OnOff): String @public(api: "HelloWorld", method: "testEnum", roles: { Internal: true, External: true, Remote: true, Public: true })
}
extend type Mutation {
  HelloWorld_operation(req: TestInput): TestResult @public(api: "HelloWorld", method: "operation", roles: { Internal: true, External: true, Remote: true, Public: true })
}

# -- Input: TestInput --
input TestInput @input {
  data: String
  urgent: Boolean
}
# -- Type: TypeA --
type TypeA @type {
  name: String
}
# -- Type: JavaScript --
type JavaScript @type {
  aString: String
  aNumber: Float
  aBoolean: Boolean
  aObject: Boolean
  anEnum: String
  aConst: Float
  aDate: Date
  anAny: ANY
  # aVoid: #VOID
  aNull: JSON
  aNever: JSON
  aStringArray: [String]
  aNumArray: [Float]
  aType: TypeA
}
# -- Type: TestResult --
type TestResult @type {
  res: String
  versions: [String]
  bool: Boolean
  state: OnOff
  sub: TypeA
  subs: [TypeA]
  str: String
  strs: [String]
}

# -- Metadata Types --
type VarMetadata @metadata {
  ref: String
  kind: String
  item: VarMetadata
}
type InputMetadata @metadata {
  ref: String
  kind: String
  build: VarMetadata
  item: VarMetadata
}
type ResultMetadata @metadata {
  ref: String
  kind: String
  build: VarMetadata
  item: VarMetadata
}
type EnumMetadata @metadata {
  kind: String
  name: String
  ref: String
  options: [String]
}
type FieldMetadata @metadata {
  kind: String
  name: String
  required: Boolean
  design: JSON
  build: VarMetadata
  ref: String
  item: VarMetadata
}
type TypeMetadata @metadata {
  kind: String
  name: String
  target: String
  item: VarMetadata
  members(
    kind: String,
    name: String,
    required: Boolean,
    ref: String
  ): [FieldMetadata]
}
type HttpBindingMetadata @metadata {
  type: String
  path: String
  binder: String
}
type HttpRouteMetadata @metadata {
  target: String
  api: ApiMetadata
  method: MethodMetadata
  route: String
  alias: String
  handler: String
  verb: String
  resource: String
  model: String
  params: [String]
  code: Int
  adapter: String
}
type EventRouteMetadata @metadata {
  target: String
  api: ApiMetadata
  method: MethodMetadata
  route: String
  alias: String
  handler: String
  source: String
  resource: String
  objectFilter: String
  actionFilter: String
  adapter: String
}
type MethodMetadata @metadata {
  target: String
  api: ApiMetadata
  host: String
  alias: String
  name: String
  design: JSON
  auth: String
  roles: JSON
  query: Boolean
  mutation: Boolean
  resolver: Boolean
  input: InputMetadata
  result: ResultMetadata
  select: JSON
  contentType: String
  bindings(
    type: String,
    path: String,
    binder: String
  ): [HttpBindingMetadata]
  http(
    target: String,
    route: String,
    alias: String,
    handler: String,
    verb: String,
    resource: String,
    model: String,
    code: Int,
    adapter: String
  ): [HttpRouteMetadata]
  events(
    target: String,
    route: String,
    alias: String,
    handler: String,
    source: String,
    resource: String,
    objectFilter: String,
    actionFilter: String,
    adapter: String
  ): [EventRouteMetadata]
  source: String
}
type ApiMetadata @metadata {
  target: String
  name: String
  alias: String
  methods(
    target: String,
    host: String,
    alias: String,
    name: String,
    auth: String,
    query: Boolean,
    mutation: Boolean,
    resolver: Boolean,
    contentType: String,
    source: String
  ): [MethodMetadata]
  routes(
    target: String,
    route: String,
    alias: String,
    handler: String,
    verb: String,
    resource: String,
    model: String,
    code: Int,
    adapter: String
  ): [HttpRouteMetadata]
  events(
    target: String,
    route: String,
    alias: String,
    handler: String,
    source: String,
    resource: String,
    objectFilter: String,
    actionFilter: String,
    adapter: String
  ): [EventRouteMetadata]
  source: String
}
type RelationMetadata @metadata {
  kind: String
  name: String
  required: Boolean
  item: VarMetadata
  design: JSON
  build: VarMetadata
  target: String
  entityMetadata: EntityMetadata
  propertyName: String
  relationType: String
  inverseEntityMetadata: EntityMetadata
  inverseRelation: RelationMetadata
  joinColumns: [ColumnMetadata]
}
type EntityMetadata @metadata {
  kind: String
  target: String
  name: String
  members(
    kind: String,
    name: String,
    required: Boolean,
    ref: String
  ): [FieldMetadata]
  columns: [ColumnMetadata]
  primaryColumns: [ColumnMetadata]
  relations(
    kind: String,
    name: String,
    required: Boolean,
    target: String,
    propertyName: String,
    relationType: String
  ): [RelationMetadata]
}
type ColumnMetadata @metadata {
  kind: String
  name: String
  required: Boolean
  design: JSON
  build: VarMetadata
  target: String
  entityMetadata: EntityMetadata
  propertyName: String
  type: String
  precision: Int
  scale: Int
  length: String
  width: Int
  comment: String
  isPrimary: Boolean
  isNullable: Boolean
  isGenerated: Boolean
  isCreateDate: Boolean
  isUpdateDate: Boolean
  isVersion: Boolean
  isVirtual: Boolean
}
type DatabaseMetadata @metadata {
  target: String
  alias: String
  targets: [String]
  entities(
    kind: String,
    target: String,
    name: String
  ): [EntityMetadata]
  columns(
    kind: String,
    name: String,
    required: Boolean,
    target: String,
    propertyName: String,
    type: String,
    precision: Int,
    scale: Int,
    length: String,
    width: Int,
    comment: String,
    isPrimary: Boolean,
    isNullable: Boolean,
    isGenerated: Boolean,
    isCreateDate: Boolean,
    isUpdateDate: Boolean,
    isVersion: Boolean,
    isVirtual: Boolean
  ): [ColumnMetadata]
  relations(
    kind: String,
    name: String,
    required: Boolean,
    target: String,
    propertyName: String,
    relationType: String
  ): [RelationMetadata]
}
type InjectMetadata @metadata {
  resource: String
  target: String
  index: Int
}
type HandlerMetadata @metadata {
  service: String
  method: String
  target: String
  source: String
}
type ServiceMetadata @metadata {
  target: String
  name: String
  alias: String
  dependencies(
    resource: String,
    target: String,
    index: Int
  ): [InjectMetadata]
  handlers(
    service: String,
    method: String,
    target: String,
    source: String
  ): [HandlerMetadata]
  initializer: HandlerMetadata
  selector: HandlerMetadata
  activator: HandlerMetadata
  releasor: HandlerMetadata
  source: String
}
type ProxyMetadata @metadata {
  target: String
  name: String
  alias: String
  application: String
  functionName: String
  dependencies(
    resource: String,
    target: String,
    index: Int
  ): [InjectMetadata]
  handlers(
    service: String,
    method: String,
    target: String,
    source: String
  ): [HandlerMetadata]
  initializer: HandlerMetadata
  selector: HandlerMetadata
  activator: HandlerMetadata
  releasor: HandlerMetadata
  source: String
}
type DecoratorMetadata @metadata {
  decorator: String
  count: Int
  targets: [String]
}
type DecorationMetadata @metadata {
  decorator: String
  ordinal: Int
  target: String
  propertyKey: String
  index: Int
  args: JSON
}
type MetadataRegistry @metadata {
  RegistryMetadata(
    kind: String,
    name: String,
    target: String
  ): [TypeMetadata]
  DecoratorMetadata(
    decorator: String,
    count: Int
  ): [DecoratorMetadata]
  DecorationMetadata(
    decorator: String,
    ordinal: Int,
    target: String,
    propertyKey: String,
    index: Int
  ): [DecorationMetadata]
  ApiMetadata(
    target: String,
    name: String,
    alias: String,
    source: String
  ): [ApiMetadata]
  ServiceMetadata(
    target: String,
    name: String,
    alias: String,
    source: String
  ): [ServiceMetadata]
  ProxyMetadata(
    target: String,
    name: String,
    alias: String,
    application: String,
    functionName: String,
    source: String
  ): [ProxyMetadata]
  DatabaseMetadata(
    target: String,
    alias: String
  ): [DatabaseMetadata]
  EntityMetadata(
    kind: String,
    target: String,
    name: String
  ): [EntityMetadata]
  ColumnMetadata(
    kind: String,
    name: String,
    required: Boolean,
    target: String,
    propertyName: String,
    type: String,
    precision: Int,
    scale: Int,
    length: String,
    width: Int,
    comment: String,
    isPrimary: Boolean,
    isNullable: Boolean,
    isGenerated: Boolean,
    isCreateDate: Boolean,
    isUpdateDate: Boolean,
    isVersion: Boolean,
    isVirtual: Boolean
  ): [ColumnMetadata]
  RelationMetadata(
    kind: String,
    name: String,
    required: Boolean,
    target: String,
    propertyName: String,
    relationType: String
  ): [RelationMetadata]
  EnumMetadata(
    kind: String,
    name: String,
    ref: String
  ): [EnumMetadata]
  InputMetadata(
    kind: String,
    name: String,
    target: String
  ): [TypeMetadata]
  TypeMetadata(
    kind: String,
    name: String,
    target: String
  ): [TypeMetadata]
  MethodMetadata(
    target: String,
    host: String,
    alias: String,
    name: String,
    auth: String,
    query: Boolean,
    mutation: Boolean,
    resolver: Boolean,
    contentType: String,
    source: String
  ): [MethodMetadata]
  ResolverMetadata(
    target: String,
    host: String,
    alias: String,
    name: String,
    auth: String,
    query: Boolean,
    mutation: Boolean,
    resolver: Boolean,
    contentType: String,
    source: String
  ): [MethodMetadata]
  HttpRouteMetadata(
    target: String,
    route: String,
    alias: String,
    handler: String,
    verb: String,
    resource: String,
    model: String,
    code: Int,
    adapter: String
  ): [HttpRouteMetadata]
  EventRouteMetadata(
    target: String,
    route: String,
    alias: String,
    handler: String,
    source: String,
    resource: String,
    objectFilter: String,
    actionFilter: String,
    adapter: String
  ): [EventRouteMetadata]
}
